// Suggestions while typing an item name — skewed toward things people
// actually forget they own (seasonal gear, tools, spares), same spirit as
// CATEGORY_PRESETS. Not exhaustive, just broad enough to be useful.
export const ITEM_NAME_SUGGESTIONS = [
  // Tools
  "Screwdriver",
  "Hammer",
  "Wrench",
  "Pliers",
  "Drill",
  "Tape Measure",
  "Spirit Level",
  "Hand Saw",
  "Allen Keys",
  "Socket Set",
  "Utility Knife",
  "Staple Gun",
  "Soldering Iron",
  // Seasonal & sports gear
  "Skis",
  "Ski Poles",
  "Ski Boots",
  "Ski Jacket",
  "Snowboard",
  "Snow Shovel",
  "Snow Pants",
  "Sled",
  "Ice Skates",
  "Tennis Racket",
  "Badminton Racket",
  "Football",
  "Basketball",
  "Volleyball",
  "Swimming Goggles",
  "Snorkel Set",
  "Diving Fins",
  "Yoga Mat",
  "Dumbbells",
  "Jump Rope",
  "Fishing Rod",
  "Camping Tent",
  "Sleeping Bag",
  "Hiking Poles",
  "Hiking Boots",
  "Bike Pump",
  "Bike Helmet",
  "Roller Skates",
  "Skateboard",
  // Clothing & footwear
  "Winter Boots",
  "Summer Sandals",
  "Sandals",
  "Rain Boots",
  "Socks",
  "Gloves",
  "Scarf",
  "Wool Hat",
  "Swimsuit",
  "Raincoat",
  "Umbrella",
  // Household spares
  "Spare Keys",
  "Light Bulbs",
  "Fuses",
  "Extension Cord",
  "Power Strip",
  "Duct Tape",
  "Super Glue",
  "Batteries",
  "Flashlight",
  "Candles",
  "Sewing Kit",
  "First Aid Kit",
  "Thermometer",
  "Padlock",
  "Scissors",
  // Electronics
  "Phone Charger",
  "Laptop Charger",
  "Old Phone",
  "Power Bank",
  "Remote Control",
  "HDMI Cable",
  "USB Cable",
  "Travel Adapter",
  "Camera",
  "Tripod",
  "Headphones",
  // Documents
  "Passport",
  "Birth Certificate",
  "Insurance Documents",
  "Warranty Papers",
  "Marriage Certificate",
  "Car Manual",
  // Holiday & decorations
  "Christmas Lights",
  "Christmas Ornaments",
  "Easter Decorations",
  "Halloween Costume",
  "Gift Wrap",
  // Luggage & travel
  "Suitcase",
  "Travel Pillow",
  "Packing Cubes",
  "Beach Towel",
  "Beach Umbrella",
  "Cooler Box",
  // Bags
  "Bag",
  "Backpack",
  "Gym Bag",
  "Tote Bag",
  "Laptop Bag",
  // Kids
  "Stroller",
  "Car Seat",
  "Board Games",
  "Puzzle",
  // Garden
  "Garden Hose",
  "Pruning Shears",
  "Rake",
  "Shovel",
  "Watering Can",
].sort();
